import { Loop } from '@/types/loop';

export const mockLoops: Loop[] = [
  {
    id: '1',
    title: 'Morning Routine',
    description: 'Start the day right with meditation, exercise, and journaling',
    type: 'daily',
    status: 'active',
    totalTasks: 5,
    completedTasks: 3,
    createdAt: new Date('2025-10-15'),
    updatedAt: new Date('2025-10-30'),
    lastCompletedAt: new Date('2025-10-30'),
    reset_rule: 'daily',
    last_reset: '2025-11-06',
    currentStreak: 12,
    longestStreak: 21,
    completionHistory: [
      { date: '2025-10-30', completed: 3, total: 5 },
      { date: '2025-10-29', completed: 5, total: 5 },
      { date: '2025-10-28', completed: 4, total: 5 },
    ],
  },
  {
    id: '2',
    title: 'Code Review',
    description: 'Review pull requests and provide feedback to team',
    type: 'work',
    status: 'active',
    totalTasks: 4,
    completedTasks: 4,
    createdAt: new Date('2025-10-20'),
    updatedAt: new Date('2025-10-30'),
    lastCompletedAt: new Date('2025-10-30'),
    reset_rule: 'daily',
    last_reset: '2025-11-06',
    currentStreak: 5,
    longestStreak: 10,
    completionHistory: [
      { date: '2025-10-30', completed: 4, total: 4 },
      { date: '2025-10-29', completed: 4, total: 4 },
    ],
  },
  {
    id: '3',
    title: 'Learning Spanish',
    description: 'Daily practice with Duolingo and conversation',
    type: 'personal',
    status: 'active',
    totalTasks: 3,
    completedTasks: 1,
    createdAt: new Date('2025-10-01'),
    updatedAt: new Date('2025-10-30'),
    lastCompletedAt: new Date('2025-10-30'),
    reset_rule: 'weekly',
    last_reset: '2025-11-04',
    currentStreak: 8,
    longestStreak: 15,
    completionHistory: [
      { date: '2025-10-30', completed: 1, total: 3 },
      { date: '2025-10-29', completed: 2, total: 3 },
    ],
  },
  {
    id: '4',
    title: 'Standup & Planning',
    description: 'Daily standup and sprint planning activities',
    type: 'work',
    status: 'active',
    totalTasks: 2,
    completedTasks: 2,
    createdAt: new Date('2025-10-28'),
    updatedAt: new Date('2025-10-30'),
    lastCompletedAt: new Date('2025-10-30'),
    reset_rule: 'daily',
    last_reset: '2025-11-06',
    currentStreak: 3,
    longestStreak: 3,
    completionHistory: [
      { date: '2025-10-30', completed: 2, total: 2 },
    ],
  },
  {
    id: '5',
    title: 'Evening Wind Down',
    description: 'Read, reflect, and prepare for tomorrow',
    type: 'daily',
    status: 'active',
    totalTasks: 4,
    completedTasks: 0,
    createdAt: new Date('2025-10-15'),
    updatedAt: new Date('2025-10-29'),
    reset_rule: 'daily',
    last_reset: '2025-11-06',
    currentStreak: 0,
    longestStreak: 7,
    completionHistory: [
      { date: '2025-10-29', completed: 3, total: 4 },
      { date: '2025-10-28', completed: 4, total: 4 },
    ],
  },
  {
    id: '6',
    title: 'Fitness Goals',
    description: 'Workout, track nutrition, and recovery',
    type: 'personal',
    status: 'active',
    totalTasks: 6,
    completedTasks: 4,
    createdAt: new Date('2025-10-01'),
    updatedAt: new Date('2025-10-30'),
    lastCompletedAt: new Date('2025-10-30'),
    reset_rule: 'manual',
    currentStreak: 18,
    longestStreak: 25,
    completionHistory: [
      { date: '2025-10-30', completed: 4, total: 6 },
      { date: '2025-10-29', completed: 5, total: 6 },
    ],
  },
];

export default mockLoops;

